---
- name: Enable rpm fusion
  dnf:
    name:
      - "{{ rpm_fusion_free }}"
      - "{{ rpm_fusion_nonfree }}"
    state: present
  when: enable_rpm_fusion

- name: Install packages by list
  dnf:
    name: "{{ packages }}"
    state: present
  when: packages | length > 1

- name: Delete packages
  dnf:
    name: "{{ packages_to_remove }}"
    state: absent
  when: packages_to_remove | length > 1

- name: Start services
  systemd:
      name: "{{ item }}"
      state: started
  with_items: "{{ start_services }}"
  when: start_services

- name: Enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ enable_services }}"
  when: enable_services

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
