---
- name: Enable rpm fusion
  dnf:
    name:
      - "{{ rpm_fusion_free }}"
      - "{{ rpm_fusion_nonfree }}"
    state: present

- name: Install packages by list
  dnf:
    name:
      - keepassxc
      - vlc
      - mpv
      - anki
      - zsh
      - mc
      - strace
      - dnf-utils
      - screen
      - restic
      - vim
      - cowsay
    state: present

- name: Enable and start services
  systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
  with_items:
    - firewalld
    - sshd
